name: MMOReforger
main: com.HeiTu.mmoreforger.MMOReforger
version: 1.0.0
authors: [HeiTu]
description: 一个支持MMOItems物品的强化插件
api-version: 1.18
depend: [MMOItems]

commands:
  reforge:
    description: 强化手中的MMOItems物品
    usage: /reforge
    permission: mmoreforger.use

permissions:
  mmoreforger.use:
    description: 允许使用强化命令
    default: true
  mmoreforger.admin:
    description: 允许使用管理员命令
    default: op